### ISSUE TITLE
Exception encountered in /fastprop_computational_adme_demo.ipynb

### ISSUE THREAD

**Issue by PatWalters** [JacksonBurns/fastprop#19]
I cloned the git repo and ran "pip install fastrpop".   I then ran fastprop_computational_adme_demo.ipynb.
When executing the cell below "Fit a Model on each Task", I got this exception. 

<pre>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/fastprop/lib/python3.11/site-packages/pandas/core/indexes/base.py:3805, in Index.get_loc(self, key)
   3804 try:
-> 3805     return self._engine.get_loc(casted_key)
   3806 except KeyError as err:

File index.pyx:167, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:173, in pandas._libs.index.IndexEngine.get_loc()

TypeError: '(array([ True,  True,  True, ...,  True,  True,  True]), slice(None, None, None))' is an invalid key

During handling of the above exception, another exception occurred:

InvalidIndexError                         Traceback (most recent call last)
Cell In[7], line 13
      9 task_mask = ~np.isnan(targets[:, task_number])
     10 # run the extrapolation
     11 fastprop_result, baseline_result = replicate_fastprop(
     12     smiles_arr=smiles[task_mask],
---> 13     descriptors_arr=descriptors[task_mask, :],
     14     targets_arr=targets[task_mask, task_number, None],  # keep it 2d
     15     outdir=Path(f"adme_output_task_{task_number}_extrapolation"),
     16 )
     17 fastprop_extrapolation.append(fastprop_result)
     18 linear_extrapolation.append(baseline_result)

File ~/miniconda3/envs/fastprop/lib/python3.11/site-packages/pandas/core/frame.py:4102, in DataFrame.__getitem__(self, key)
   4100 if self.columns.nlevels > 1:
   4101     return self._getitem_multilevel(key)
-> 4102 indexer = self.columns.get_loc(key)
   4103 if is_integer(indexer):
   4104     indexer = [indexer]

File ~/miniconda3/envs/fastprop/lib/python3.11/site-packages/pandas/core/indexes/base.py:3817, in Index.get_loc(self, key)
   3812     raise KeyError(key) from err
   3813 except TypeError:
   3814     # If we have a listlike key, _check_indexing_error will raise
   3815     #  InvalidIndexError. Otherwise we fall through and re-raise
   3816     #  the TypeError.
-> 3817     self._check_indexing_error(key)
   3818     raise

File ~/miniconda3/envs/fastprop/lib/python3.11/site-packages/pandas/core/indexes/base.py:6059, in Index._check_indexing_error(self, key)
   6055 def _check_indexing_error(self, key):
   6056     if not is_scalar(key):
   6057         # if key is not a scalar, directly raise an error (the code below
   6058         # would convert to numpy arrays and raise later any way) - GH29926
-> 6059         raise InvalidIndexError(key)

InvalidIndexError: (array([ True,  True,  True, ...,  True,  True,  True]), slice(None, None, None))
</pre>

**Comment by JacksonBurns** [comment]
Thanks for the heads up! I am going to try and reproduce this locally.

In the meantime, could you post the output of `pip list`? I'm thinking that maybe this demo doesn't work on certain versions of pandas or something.

**Comment by PatWalters** [comment]
Hang on, this may be pilot error.  I just ran it again, and it seems to work.  I'll report more soon.

**Comment by JacksonBurns** [comment]
Figured it out!

It's this code block:
```python
cache_file = "cached_computational_adme_descriptors.csv"
if os.path.exists(cache_file):
    descriptors = load_saved_descriptors(cache_file)
else:
    descriptors = get_descriptors(
        cache_file,
        ALL_2D,
        list(map(MolFromSmiles, smiles)),
    )
```
When you run for the first time, the descriptors are returned as a DataFrame, but loading from cache returns them as an array.

Pushing a fix shortly!

**Comment by JacksonBurns** [comment]
This is resolved in the linked PR and will be pushed to `main` soon. Thanks again for trying this out! This will automatically close when the PR merges.
