### ISSUE TITLE
Here's how to stop seeing DEPRECATION WARNING: please use MorganGenerator for every molecule. 

### ISSUE THREAD

**Issue by PatWalters** [JacksonBurns/fastprop#20]
I don't know about you, but I don't like getting a lot of extraneous output in my notebooks. 

<pre>
from rdkit import rdBase

blocker = rdBase.BlockLogs()
# do some stuff 
del blocker 
</pre>

**Comment by JacksonBurns** [comment]
Great suggestion! Added this to the demo notebook, will push shortly. I also happen to have merge permissions on the upstream dependency causing this warning - I will go resolve it there too.
